- name: Download Helm
  get_url:
    url: "{{ URL_GET_HELM }}"
    dest: /tmp/get_helm.sh
    mode: 0755
  ignore_errors: true
  register: download_helm

- name: instalando o Helm
  shell:
    /tmp/get_helm.sh
  register: install_helm

- name: var helm
  debug: var=install_helm